v0.3.6
you can now run RepeatModeler on the cluster, using the USE_CLUSTER option in the config file

diff --git a/genome-annotation b/genome-annotation
--- a/genome-annotation
+++ b/genome-annotation
@@ -1,5 +1,5 @@
 #!/bin/bash
-## v0.3.5
+## v0.3.6
 ## Pipeline to annotate genome using BRAKER and GeMoMa
 ## authors: Dan MacGuigan, Nate Backenstose, Christopher Osborne
 
@@ -106,6 +106,10 @@ done
 # RUN STEPS 5-8 on the cluster                               #
 ##############################################################
 
+# make sure genome has UNIX line endings
+dos2unix ${ANNOTATION_DIR_CLUSTER}/${GENOME_DIR}/${GENOME_FILE}
+dos2unix ${ANNOTATION_DIR_BOTTLEROCKET}/${GENOME_DIR}/${GENOME_FILE}
+
 ### STEP 1 ###
 ## GENERATE CUSTOM REPEAT LIBRARY
 ## on the KrabLab Bottlerocket
@@ -119,9 +123,17 @@ if [[ "${step}" == 1 ]]; then
 	if [ -z ${GENOME_FILE+x} ]; then echo "  GENOME_FILE is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  GENOME_FILE='$GENOME_FILE'"; fi
 	if [ -z ${REPEAT_LIBRARY_NAME+x} ]; then echo "  REPEAT_LIBRARY_NAME is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  REPEAT_LIBRARY_NAME='$REPEAT_LIBRARY_NAME'"; fi
 	if [ -z ${RMODEL_THREADS+x} ]; then echo "  RMODEL_THREADS is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RMODEL_THREADS='$RMODEL_THREADS'"; fi
+	if [ -z ${RMODEL_RAM+x} ]; then echo "  RMODEL_RAM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RMODEL_RAM='$RMODEL_RAM'"; fi
+	if [ -z ${USE_CLUSTER+x} ]; then echo "  USE_CLUSTER is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  USE_CLUSTER='$USE_CLUSTER'"; fi
 	echo ""
-	mkdir -p "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles" # create logFiles directory
-	bash "${ANNOTATION_DIR_BOTTLEROCKET}"/scripts/generate_repeat_lib.sh ${SPECIES} ${GENOME_DIR} ${GENOME_FILE} ${REPEAT_LIBRARY_NAME} ${RMODEL_THREADS} > "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles/${SPECIES}_generate_repeat_lib.out" 2> "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles/${SPECIES}_generate_repeat_lib.error"
+	if [ ${USE_CLUSTER} = "yes" ]
+	then
+		mkdir -p "${ANNOTATION_DIR_CLUSTER}/logFiles" # create logFiles directory
+		sbatch --job-name="${SPECIES}_RMASK" --ntasks-per-node=${RMODEL_THREADS} --mem=${RMODEL_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_generate_repeat_lib.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_generate_repeat_lib.err" ./scripts/generate_repeat_lib.sh ${SPECIES} ${ANNOTATION_DIR_CLUSTER} ${GENOME_DIR} ${GENOME_FILE} ${REPEAT_LIBRARY_NAME} ${RMODEL_THREADS}
+	else
+		mkdir -p "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles" # create logFiles directory
+		bash "${ANNOTATION_DIR_BOTTLEROCKET}"/scripts/generate_repeat_lib.sh ${SPECIES} ${GENOME_DIR} ${GENOME_FILE} ${REPEAT_LIBRARY_NAME} ${RMODEL_THREADS} > "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles/${SPECIES}_generate_repeat_lib.out" 2> "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles/${SPECIES}_generate_repeat_lib.error"
+	fi
 fi
 
 ### STEP 2 ###
