GeMoMa filtering options

diff --git a/genome-annotation b/genome-annotation
--- a/genome-annotation
+++ b/genome-annotation
@@ -1,5 +1,5 @@
 #!/bin/bash
-## v0.3.4
+## v0.3.5
 ## Pipeline to annotate genome using BRAKER and GeMoMa
 ## authors: Dan MacGuigan, Nate Backenstose, Christopher Osborne
 
@@ -252,9 +252,9 @@ if [[ "${step}" == 7 ]]; then
 	echo ""
 	mkdir -p "${ANNOTATION_DIR_CLUSTER}/logFiles" # create logFiles directory
 	if [[ "${USE_HISAT2_RNA_SEQ}" == "YES" ]]; then
-		sbatch --job-name="${SPECIES}_GEMOMA" --ntasks-per-node=${GEMOMA_THREADS} --mem=${GEMOMA_JOB_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.err" ./scripts/run_GEMOMA_RNA-seq.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${GEMOMA_THREADS} ${GEMOMA_RAM} ${ANNOTATION_DIR_CLUSTER} ${GEMOMA_REFS} ${USE_HISAT2_RNA_SEQ} ${HISAT2_RNA_LIB_TYPE} ${USE_CUSTOM_RNA_SEQ} ${CUSTOM_RNA_BAM} ${CUSTOM_RNA_LIB_TYPE}
+		sbatch --job-name="${SPECIES}_GEMOMA" --ntasks-per-node=${GEMOMA_THREADS} --mem=${GEMOMA_JOB_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.err" ./scripts/run_GEMOMA_RNA-seq.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${GEMOMA_THREADS} ${GEMOMA_RAM} ${ANNOTATION_DIR_CLUSTER} ${GEMOMA_REFS} ${USE_HISAT2_RNA_SEQ} ${HISAT2_RNA_LIB_TYPE} ${USE_CUSTOM_RNA_SEQ} ${CUSTOM_RNA_BAM} ${CUSTOM_RNA_LIB_TYPE} ${GEMOMA_SCORE_AA_FILTER} ${GEMOMA_FILTER_ONLY}
 	elif [[ "${USE_CUSTOM_RNA_SEQ}" == "YES" ]]; then
-		sbatch --job-name="${SPECIES}_GEMOMA" --ntasks-per-node=${GEMOMA_THREADS} --mem=${GEMOMA_JOB_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.err" ./scripts/run_GEMOMA_RNA-seq.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${GEMOMA_THREADS} ${GEMOMA_RAM} ${ANNOTATION_DIR_CLUSTER} ${GEMOMA_REFS} ${USE_HISAT2_RNA_SEQ} ${HISAT2_RNA_LIB_TYPE} ${USE_CUSTOM_RNA_SEQ} ${CUSTOM_RNA_BAM} ${CUSTOM_RNA_LIB_TYPE}
+		sbatch --job-name="${SPECIES}_GEMOMA" --ntasks-per-node=${GEMOMA_THREADS} --mem=${GEMOMA_JOB_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.err" ./scripts/run_GEMOMA_RNA-seq.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${GEMOMA_THREADS} ${GEMOMA_RAM} ${ANNOTATION_DIR_CLUSTER} ${GEMOMA_REFS} ${USE_HISAT2_RNA_SEQ} ${HISAT2_RNA_LIB_TYPE} ${USE_CUSTOM_RNA_SEQ} ${CUSTOM_RNA_BAM} ${CUSTOM_RNA_LIB_TYPE} ${GEMOMA_SCORE_AA_FILTER} ${GEMOMA_FILTER_ONLY}
 	else
 		sbatch --job-name="${SPECIES}_GEMOMA" --ntasks-per-node=${GEMOMA_THREADS} --mem=${GEMOMA_JOB_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_GEMOMA.err" ./scripts/run_GEMOMA.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${GEMOMA_THREADS} ${GEMOMA_RAM} ${ANNOTATION_DIR_CLUSTER} ${GEMOMA_REFS} ${GEMOMA_SCORE_AA_FILTER} ${GEMOMA_FILTER_ONLY}
 	fi
@@ -276,22 +276,23 @@ if [[ "${step}" == 8 ]]; then
 	if [ -z ${EVM_THREADS+x} ]; then echo "  EVM_THREADS is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  EVM_THREADS='$EVM_THREADS'"; fi
 	if [ -z ${EVM_RAM+x} ]; then echo "  EVM_RAM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  EVM_RAM='$EVM_RAM'"; fi
 	if [ -z ${MASKED_GENOME_FILE+x} ]; then echo "  MASKED_GENOME_FILE is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  MASKED_GENOME_FILE='$MASKED_GENOME_FILE'"; fi
+	if [ -z ${GEMOMA_SCORE_AA_FILTER+x} ]; then echo "  GEMOMA_SCORE_AA_FILTER is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  GEMOMA_SCORE_AA_FILTER='$GEMOMA_SCORE_AA_FILTER'"; fi
 	echo ""
 	mkdir -p "${ANNOTATION_DIR_CLUSTER}/logFiles" # create logFiles directory
 	echo "converting BRAKER and GeMoMa files for EVM"
 	cd ${ANNOTATION_DIR_CLUSTER} # create directory for EVM
-	mkdir -p ${SPECIES}_EVM_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}
-	mkdir -p ${SPECIES}_EVM_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}/evidence
-	cd ${SPECIES}_EVM_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}/evidence
+	mkdir -p ${SPECIES}_EVM_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}-SCORE-${GEMOMA_SCORE_AA_FILTER}
+	mkdir -p ${SPECIES}_EVM_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}-SCORE-${GEMOMA_SCORE_AA_FILTER}/evidence
+	cd ${SPECIES}_EVM_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}-SCORE-${GEMOMA_SCORE_AA_FILTER}/evidence
 	# make copies of gene predictions and merge
 	cp ${ANNOTATION_DIR_CLUSTER}/${SPECIES}_BRAKER/braker.gtf braker.gtf
-	cp ${ANNOTATION_DIR_CLUSTER}/${SPECIES}_GeMoMa/GeMoMa_combined/final_annotation.gff gemoma.gff3
+	cp ${ANNOTATION_DIR_CLUSTER}/${SPECIES}_GeMoMa/GeMoMa_combined/filter_score_${GEMOMA_SCORE_AA_FILTER}/final_annotation.gff gemoma.gff3
 	# convert input files to EVM format
 	/projects/academic/tkrabben/software/EvidenceModeler/EVidenceModeler/EvmUtils/misc/GeMoMa_gff_to_gff3.pl gemoma.gff3 > gemoma.EVM.gff3
 	/projects/academic/tkrabben/software/EvidenceModeler/EVidenceModeler/EvmUtils/misc/braker_GTF_to_EVM_GFF3.pl braker.gtf > braker.EVM.gff3
 	cd ${ANNOTATION_DIR_CLUSTER}
 	echo "submitting EVM job"
-	sbatch --job-name="${SPECIES}_EVM" --ntasks-per-node=${EVM_THREADS} --mem=${EVM_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}_EVM.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}_EVM.err" ./scripts/run_EVM.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${ANNOTATION_DIR_CLUSTER} ${BRAKER_WEIGHT} ${GEMOMA_WEIGHT} ${EVM_THREADS}
+	sbatch --job-name="${SPECIES}_EVM" --ntasks-per-node=${EVM_THREADS} --mem=${EVM_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}-SCORE-${GEMOMA_SCORE_AA_FILTER}_EVM.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_B${BRAKER_WEIGHT}_G${GEMOMA_WEIGHT}-SCORE-${GEMOMA_SCORE_AA_FILTER}_EVM.err" ./scripts/run_EVM.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${ANNOTATION_DIR_CLUSTER} ${BRAKER_WEIGHT} ${GEMOMA_WEIGHT} ${EVM_THREADS} ${GEMOMA_SCORE_AA_FILTER}
 fi
 
 ### STEP 9 ###
@@ -307,12 +308,13 @@ if [[ "${step}" == 9 ]]; then
 	if [ -z ${GENOME_FILE+x} ]; then echo "  GENOME_FILE is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  GENOME_FILE='$GENOME_FILE'"; fi
 	if [ -z ${BRAKER_WEIGHT_EGG+x} ]; then echo "  BRAKER_WEIGHT_EGG is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  BRAKER_WEIGHT_EGG='$BRAKER_WEIGHT_EGG'"; fi
 	if [ -z ${GEMOMA_WEIGHT_EGG+x} ]; then echo "  GEMOMA_WEIGHT_EGG is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  GEMOMA_WEIGHT_EGG='$GEMOMA_WEIGHT_EGG'"; fi
+	if [ -z ${GEMOMA_SCORE_AA_FILTER+x} ]; then echo "  GEMOMA_SCORE_AA_FILTER is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  GEMOMA_SCORE_AA_FILTER='$GEMOMA_SCORE_AA_FILTER'"; fi
 	if [ -z ${EGG_THREADS+x} ]; then echo "  EGG_THREADS is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  EGG_THREADS='$EGG_THREADS'"; fi
 	if [ -z ${EGG_RAM+x} ]; then echo "  EGG_RAM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  EGG_RAM='$EGG_RAM'"; fi
 	if [ -z ${EGGNOG_OPTIONS+x} ]; then echo "  EGGNOG_OPTIONS is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  EGGNOG_OPTIONS='$EGGNOG_OPTIONS'"; fi
 	echo ""
 	cd ${ANNOTATION_DIR_CLUSTER}
-	mkdir -p ${SPECIES}_EVM_B${BRAKER_WEIGHT_EGG}_G${GEMOMA_WEIGHT_EGG}_eggNOG
+	mkdir -p ${SPECIES}_EVM_B${BRAKER_WEIGHT_EGG}_G${GEMOMA_WEIGHT_EGG}-SCORE-${GEMOMA_SCORE_AA_FILTER}_eggNOG
 	echo "submitting eggNOG mapper job"
-	sbatch --job-name="${SPECIES}_eggNOG" --ntasks-per-node=${EGG_THREADS} --mem=${EGG_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_B${BRAKER_WEIGHT_EGG}_G${GEMOMA_WEIGHT_EGG}_EVM_eggNOG.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_B${BRAKER_WEIGHT_EGG}_G${GEMOMA_WEIGHT_EGG}_EVM_eggNOG.err" ./scripts/run_eggNOG.sh ${SPECIES}  ${ANNOTATION_DIR_CLUSTER} ${BRAKER_WEIGHT_EGG} ${GEMOMA_WEIGHT_EGG} ${EGG_THREADS} ${EGGNOG_OPTIONS}
+	sbatch --job-name="${SPECIES}_eggNOG" --ntasks-per-node=${EGG_THREADS} --mem=${EGG_RAM} --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_B${BRAKER_WEIGHT_EGG}_G${GEMOMA_WEIGHT_EGG}_EVM_eggNOG.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_B${BRAKER_WEIGHT_EGG}_G${GEMOMA_WEIGHT_EGG}_EVM_eggNOG.err" ./scripts/run_eggNOG.sh ${SPECIES}  ${ANNOTATION_DIR_CLUSTER} ${BRAKER_WEIGHT_EGG} ${GEMOMA_WEIGHT_EGG} ${EGG_THREADS} ${EGGNOG_OPTIONS} ${GEMOMA_SCORE_AA_FILTER}
 fi
