v0.4
allows steps 3 and 4 to be run on the cluster

diff --git a/genome-annotation b/genome-annotation
--- a/genome-annotation
+++ b/genome-annotation
@@ -1,5 +1,5 @@
 #!/bin/bash
-## v0.3.6
+## v0.4.0
 ## Pipeline to annotate genome using BRAKER and GeMoMa
 ## authors: Dan MacGuigan, Nate Backenstose, Christopher Osborne
 
@@ -21,10 +21,10 @@ Help()
    echo "Before running this pipeline, be sure to modify the input variables in 'config.txt'"
    echo ""
    echo "Annotation pipeline steps"
-   echo "Step 1: RepeatModeler [Bottlerocket]"
-   echo "Step 2: RepeatMasker [Bottlerocket]"
-   echo "Step 3: soft mask genome [Bottlerocket]"
-   echo "Step 4: map RNA-seq reads [Bottlerocket]"
+   echo "Step 1: RepeatModeler [Bottlerocket or cluster]"
+   echo "Step 2: RepeatMasker [Bottlerocket or cluster]"
+   echo "Step 3: soft mask genome [Bottlerocket or cluster]"
+   echo "Step 4: map RNA-seq reads [Bottlerocket or cluster]"
    echo "        NOTE: HISAT2 is optional but recommended. It requires Illumina RNA-seq data,"
    echo "        preferably from the species you are annotating."
    echo "        After Step 4, you must copy your ANNOTATION_DIR_BOTTLEROCKET to the cluster"
@@ -109,6 +109,7 @@ done
 ### STEP 1 ###
 ## GENERATE CUSTOM REPEAT LIBRARY
 ## on the KrabLab Bottlerocket
+## or on the UB CCR Vortex cluster
 if [[ "${step}" == 1 ]]; then
 	echo ""
 	echo "INPUT VARIABLES as specified in your config file:"
@@ -121,11 +122,11 @@ if [[ "${step}" == 1 ]]; then
 	if [ -z ${RMODEL_THREADS+x} ]; then echo "  RMODEL_THREADS is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RMODEL_THREADS='$RMODEL_THREADS'"; fi
 	if [ -z ${RMODEL_RAM+x} ]; then echo "  RMODEL_RAM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RMODEL_RAM='$RMODEL_RAM'"; fi
 	if [ -z ${RUN_LTR+x} ]; then echo "  RUN_LTR is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RUN_LTR='$RUN_LTR'"; fi
-	if [ -z ${USE_CLUSTER+x} ]; then echo "  USE_CLUSTER is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  USE_CLUSTER='$USE_CLUSTER'"; fi
+	if [ -z ${USE_CLUSTER_RM+x} ]; then echo "  USE_CLUSTER_RM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  USE_CLUSTER_RM='$USE_CLUSTER_RM'"; fi
 	if [ -z ${CONTINUE_RMODEL+x} ]; then echo "  CONTINUE_RMODEL is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  CONTINUE_RMODEL='$CONTINUE_RMODEL'"; fi
 	if [ -z ${CONTINUE_RMODEL_DIR+x} ]; then echo "  CONTINUE_RMODEL_DIR is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  CONTINUE_RMODEL_DIR='$CONTINUE_RMODEL_DIR'"; fi
 	echo ""
-	if [ ${USE_CLUSTER} = "yes" ]
+	if [ ${USE_CLUSTER_RM} = "yes" ]
 	then
 		dos2unix ${ANNOTATION_DIR_CLUSTER}/${GENOME_DIR}/${GENOME_FILE} # make sure genome has UNIX line endings
 		echo "starting RepeatModeler on the cluster"
@@ -142,7 +143,8 @@ fi
 ### STEP 2 ###
 ## RUN REPEAT MASKER
 ## on the KrabLab Bottlerocket
-## use the custom repeat library generated in step 1A
+## or on the UB CCR Vortex cluster
+## use the custom repeat library generated in step 1
 ## and species/clade specified by RM_SPECIES
 if [[ "${step}" == 2 ]]; then
 	echo ""
@@ -156,9 +158,9 @@ if [[ "${step}" == 2 ]]; then
 	if [ -z ${REPEAT_LIBRARY_NAME+x} ]; then echo "  REPEAT_LIBRARY_NAME is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  REPEAT_LIBRARY_NAME='$REPEAT_LIBRARY_NAME'"; fi
 	if [ -z ${RM_SPECIES+x} ]; then echo "  RM_SPECIES is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RM_SPECIES='$RM_SPECIES'"; fi
 	if [ -z ${RMASK_RAM+x} ]; then echo "  RMASK_RAM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RMASK_RAM='$RMASK_RAM'"; fi
-	if [ -z ${USE_CLUSTER+x} ]; then echo "  USE_CLUSTER is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  USE_CLUSTER='$USE_CLUSTER'"; fi
+	if [ -z ${USE_CLUSTER_RM+x} ]; then echo "  USE_CLUSTER_RM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  USE_CLUSTER_RM='$USE_CLUSTER_RM'"; fi
 	echo ""
-	if [ ${USE_CLUSTER} = "yes" ]
+	if [ ${USE_CLUSTER_RM} = "yes" ]
 	then
 		mkdir -p "${ANNOTATION_DIR_CLUSTER}/logFiles" # create logFiles directory
 		echo "starting RepeatMasker on the cluster"
@@ -174,7 +176,8 @@ fi
 ### STEP 3 ###
 ## RUN BEDTOOLS TO SOFT MASK GENOME
 ## on the KrabLab Bottlerocket
-## using the repeat GFF generated by step 1B
+## or on the UB CCR Vortex cluster
+## using the repeat GFF generated by step 2
 if [[ "${step}" == 3 ]]; then
 	echo ""
 	echo "INPUT VARIABLES as specified in your config file:"
@@ -184,15 +187,24 @@ if [[ "${step}" == 3 ]]; then
 	if [ -z ${GENOME_DIR+x} ]; then echo "  GENOME_DIR is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  GENOME_DIR='$GENOME_DIR'"; fi
 	if [ -z ${GENOME_FILE+x} ]; then echo "  GENOME_FILE is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  GENOME_FILE='$GENOME_FILE'"; fi
 	if [ -z ${MASKED_GENOME_FILE+x} ]; then echo "  MASKED_GENOME_FILE is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  MASKED_GENOME_FILE='$MASKED_GENOME_FILE'"; fi
+	if [ -z ${USE_CLUSTER_RM+x} ]; then echo "  USE_CLUSTER_RM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  USE_CLUSTER_RM='$USE_CLUSTER_RM'"; fi
 	echo ""
-	mkdir -p "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles" # create logFiles directory
-	bedtools maskfasta -bed "${ANNOTATION_DIR_BOTTLEROCKET}/${SPECIES}_RepeatMasker/final_repeat_mask/${SPECIES}.final_repeat_mask.gff3" -fi "${ANNOTATION_DIR_BOTTLEROCKET}/${GENOME_DIR}/${GENOME_FILE}" -fo "${ANNOTATION_DIR_BOTTLEROCKET}/${GENOME_DIR}/${MASKED_GENOME_FILE}" -soft
+	if [ ${USE_CLUSTER_RM} = "yes" ]
+	then
+		module load gcc/11.2.0 bedtools/2.30.0
+		mkdir -p "${ANNOTATION_DIR_CLUSTER}/logFiles" # create logFiles directory
+		bedtools maskfasta -bed "${ANNOTATION_DIR_CLUSTER}/${SPECIES}_RepeatMasker/final_repeat_mask/${SPECIES}.final_repeat_mask.gff3" -fi "${ANNOTATION_DIR_CLUSTER}/${GENOME_DIR}/${GENOME_FILE}" -fo "${ANNOTATION_DIR_CLUSTER}/${GENOME_DIR}/${MASKED_GENOME_FILE}" -soft
+	else
+		mkdir -p "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles" # create logFiles directory
+		bedtools maskfasta -bed "${ANNOTATION_DIR_BOTTLEROCKET}/${SPECIES}_RepeatMasker/final_repeat_mask/${SPECIES}.final_repeat_mask.gff3" -fi "${ANNOTATION_DIR_BOTTLEROCKET}/${GENOME_DIR}/${GENOME_FILE}" -fo "${ANNOTATION_DIR_BOTTLEROCKET}/${GENOME_DIR}/${MASKED_GENOME_FILE}" -soft
+	fi
 fi
 
 ### STEP 4 ###
 ## RUN HISAT2 TO MAP RNA-seq READS
 ## on the KrabLab Bottlerocket
-## use soft masked genome from step 1C
+## or on the UB CCR Vortex cluster
+## use soft masked genome from step 3
 if [[ "${step}" == 4 ]]; then
 	echo ""
 	echo "INPUT VARIABLES as specified in your config file:"
@@ -204,10 +216,20 @@ if [[ "${step}" == 4 ]]; then
 	if [ -z ${RNA_DIR+x} ]; then echo "  RNA_DIR is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RNA_DIR='$RNA_DIR'"; fi
 	if [ -z ${RNA_FILES+x} ]; then echo "  RNA_FILES is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  RNA_FILES='$RNA_FILES'"; fi
 	if [ -z ${HISAT_THREADS+x} ]; then echo "  HISAT_THREADS is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  HISAT_THREADS='$HISAT_THREADS'"; fi
+	if [ -z ${HISAT_RAM+x} ]; then echo "  HISAT_RAM is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  HISAT_RAM='$HISAT_RAM'"; fi
+	if [ -z ${USE_CLUSTER_HISAT+x} ]; then echo "  USE_CLUSTER_HISAT is unset"; echo "  please ensure all variables are specified in your config file"; exit 1; else echo "  USE_CLUSTER_HISAT='$USE_CLUSTER_HISAT'"; fi
 	echo ""
-	mkdir -p "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles" # create logFiles directory
-	bash "${ANNOTATION_DIR_BOTTLEROCKET}"/scripts/run_HISAT2.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${RNA_DIR} ${RNA_FILES} ${HISAT_THREADS} > "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles/${SPECIES}_HISAT2.out" 2> "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles/${SPECIES}_HISAT2.error"
+	if [ ${USE_CLUSTER_HISAT} = "yes" ]
+	then
+		mkdir -p "${ANNOTATION_DIR_CLUSTER}/logFiles" # create logFiles directory
+		sbatch --output="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_HISAT2.out" --error="${ANNOTATION_DIR_CLUSTER}/logFiles/${SPECIES}_HISAT2.error" --ntasks-per-node=${HISAT_THREADS} --mem=${HISAT_RAM} ${ANNOTATION_DIR_CLUSTER}/scripts/run_HISAT2_cluster.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${RNA_DIR} ${RNA_FILES} ${HISAT_THREADS} ${ANNOTATION_DIR_CLUSTER}
+	else
+		mkdir -p "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles" # create logFiles directory
+		bash "${ANNOTATION_DIR_BOTTLEROCKET}"/scripts/run_HISAT2.sh ${SPECIES} ${GENOME_DIR} ${MASKED_GENOME_FILE} ${RNA_DIR} ${RNA_FILES} ${HISAT_THREADS} > "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles/${SPECIES}_HISAT2.out" 2> "${ANNOTATION_DIR_BOTTLEROCKET}/logFiles/${SPECIES}_HISAT2.error"
+	fi
 fi
+
+USE_CLUSTER_HISAT
 
 ### STEP 5 ###
 ## DOWNLOAD REFERENCE DATA FROM NCBI
